version: '3'
services:
  mysql:
    image: mysql:5.7
    expose:
      - '3306'
    #network_mode: "host"
    ports:
      - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dataPlatform/db:/var/lib/mysql
      - ./dataPlatform/db/my.cnf:/etc/mysql/my.cnf
      - ./dataPlatform/db/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=iot
      - MYSQL_ROOT_PASSWORD=%5QWERzxc

  frontend:
    build: ./ant_frontend
    command: bash -c "npm install && npm start"
    volumes:
      - ./ant_frontend:/usr/src/app/
    ports:
      - "9001:8000"
    restart: always
    depends_on:
      - backend

  backend:
    build: ./dataPlatform/
    command: bash -c "cd iot && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./dataPlatform:/backend
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "9002:8001"
    restart: always
  # environment:
  #   - MYSQL_HOST=mysql
  #   - MYSQL_DATABASE=iot
  #    - MYSQL_ROOT_PASSWORD=%5QWERzxc

  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    ports:
      - "9000:9000"
