# Generated by Django 2.1.7 on 2019-04-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(default='', max_length=20)),
                ('summary', models.CharField(default='', max_length=256)),
                ('adcode', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
