# Generated by Django 2.1.7 on 2019-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
                ('code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('send_type', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
    ]
