# Generated by Django 2.1.7 on 2019-04-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_captcha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Captcha',
            new_name='EmailCode',
        ),
    ]
