# Generated by Django 2.1.7 on 2019-04-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_auto_20190411_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
