# Generated by Django 2.1.7 on 2019-04-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_auto_20190411_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='send_type',
            field=models.CharField(default='', max_length=15, verbose_name='请求类型'),
        ),
    ]
