# Generated by Django 2.1.7 on 2019-04-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_auto_20190411_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentAuthority',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
