# Generated by Django 2.1.7 on 2019-05-07 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.CharField(max_length=25)),
                ('type', models.IntegerField()),
                ('y', models.FloatField()),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('val', models.FloatField()),
                ('intensity', models.FloatField()),
                ('time', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('safe', models.BooleanField()),
                ('confirmed', models.BooleanField(default=False)),
                ('fPort', models.IntegerField(default=0)),
                ('reference', models.CharField(default='', max_length=100)),
                ('data', models.CharField(default='', max_length=100)),
                ('recordTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '数值表',
                'verbose_name_plural': '数值表',
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=20)),
                ('node_type', models.CharField(max_length=20)),
                ('minVal', models.IntegerField()),
                ('maxVal', models.IntegerField()),
                ('subscribe', models.BooleanField(default=False)),
                ('nodeId', models.CharField(max_length=50, unique=True)),
                ('adcode', models.CharField(max_length=15)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '数据节点',
                'verbose_name_plural': '数据节点',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('commodityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Commodity')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=20, unique=True)),
                ('count', models.IntegerField(default=1)),
                ('status', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': '搜索数据',
                'verbose_name_plural': '搜索数据',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='device_id',
            field=models.ForeignKey(blank=True, db_column='device_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_device_id', to='api.Nodes', to_field='nodeId'),
        ),
        migrations.AddField(
            model_name='data',
            name='nodeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
    ]
