# Generated by Django 2.1.7 on 2019-03-06 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('max_val', models.IntegerField()),
                ('min_val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('val', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('safe', models.BooleanField()),
                ('record_time', models.DateField()),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nodes')),
            ],
        ),
    ]
