# Generated by Django 2.1.7 on 2019-04-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.CharField(max_length=25)),
                ('type', models.IntegerField()),
                ('y', models.FloatField()),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('val', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('safe', models.BooleanField()),
                ('recordTime', models.DateTimeField()),
            ],
            options={
                'verbose_name': '数值表',
                'verbose_name_plural': '数值表',
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=20)),
                ('node_type', models.CharField(max_length=20)),
                ('minVal', models.IntegerField()),
                ('maxVal', models.IntegerField()),
                ('adcode', models.CharField(max_length=15)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'verbose_name': '数据节点',
                'verbose_name_plural': '数据节点',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('commodityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Commodity')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('range', models.FloatField()),
                ('status', models.FloatField()),
            ],
            options={
                'verbose_name': '搜索数据',
                'verbose_name_plural': '搜索数据',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='nodeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
    ]
