# Generated by Django 2.1.7 on 2019-04-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='nodeId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nodes',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
