# Generated by Django 2.1.7 on 2019-03-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodes',
            options={'verbose_name': '数据节点', 'verbose_name_plural': '数据节点'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'verbose_name': '温度', 'verbose_name_plural': '温度'},
        ),
        migrations.AlterField(
            model_name='temperature',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
    ]
