# Generated by Django 2.1.7 on 2019-04-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190425_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='data',
            name='fPort',
            field=models.IntegerField(default=0),
        ),
    ]
