# Generated by Django 2.1.7 on 2019-05-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190506_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='device_id',
            field=models.ForeignKey(db_column='device_id', default='dwdwdwdw', on_delete=django.db.models.deletion.CASCADE, related_name='data_device_id', to='api.Nodes', to_field='nodeId'),
            preserve_default=False,
        ),
    ]
