# Generated by Django 2.1.7 on 2019-05-06 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_data_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='device_id',
            field=models.ForeignKey(blank=True, db_column='device_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_device_id', to='api.Nodes', to_field='nodeId'),
        ),
        migrations.AlterField(
            model_name='data',
            name='nodeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
        migrations.AlterField(
            model_name='data',
            name='recordTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
