# Generated by Django 2.1.7 on 2019-05-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190507_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdata',
            name='keyword',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
