# Generated by Django 2.1.7 on 2019-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190506_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.CharField(default='', max_length=100),
        ),
    ]
