# Generated by Django 2.1.7 on 2019-05-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_data_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
