# Generated by Django 2.1.7 on 2019-03-06 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190306_0647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='temperature',
            new_name='Data',
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': '数值表', 'verbose_name_plural': '数值表'},
        ),
        migrations.AlterField(
            model_name='data',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
    ]
