# Generated by Django 2.1.7 on 2019-03-09 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190309_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
    ]
