# Generated by Django 2.1.7 on 2019-03-09 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190309_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='node_id',
            new_name='nodeId',
        ),
        migrations.RenameField(
            model_name='nodes',
            old_name='max_val',
            new_name='maxVal',
        ),
        migrations.RenameField(
            model_name='nodes',
            old_name='min_val',
            new_name='minVal',
        ),
        migrations.RenameField(
            model_name='nodes',
            old_name='name',
            new_name='nodeName',
        ),
        migrations.RenameField(
            model_name='nodes',
            old_name='type',
            new_name='nodeType',
        ),
        migrations.RemoveField(
            model_name='data',
            name='record_time',
        ),
        migrations.AddField(
            model_name='data',
            name='recordTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='nodeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
    ]
