# Generated by Django 2.1.7 on 2019-03-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190309_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodes',
            old_name='nodeName',
            new_name='node_name',
        ),
        migrations.RenameField(
            model_name='nodes',
            old_name='nodeType',
            new_name='node_type',
        ),
        migrations.AlterField(
            model_name='data',
            name='nodeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
    ]
