# Generated by Django 2.1.7 on 2019-03-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190315_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('range', models.FloatField()),
                ('status', models.FloatField()),
            ],
            options={
                'verbose_name': '搜索数据',
                'verbose_name_plural': '搜索数据',
            },
        ),
        migrations.AlterField(
            model_name='data',
            name='nodeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
    ]
