# Generated by Django 2.1.7 on 2019-03-20 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20190320_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='location',
        ),
        migrations.AlterField(
            model_name='data',
            name='nodeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
    ]
