# Generated by Django 2.1.7 on 2019-03-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20190320_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='name',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='sales',
            new_name='y',
        ),
        migrations.AlterField(
            model_name='data',
            name='nodeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
        ),
    ]
