# Generated by Django 2.1.7 on 2019-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_auto_20190322_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='nodeId',
        ),
        migrations.AddField(
            model_name='data',
            name='nodeId',
            field=models.ManyToManyField(to='api.Nodes'),
        ),
    ]
