# Generated by Django 2.1.7 on 2019-03-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_auto_20190322_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='nodeId',
        ),
        migrations.AddField(
            model_name='data',
            name='nodeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Nodes'),
            preserve_default=False,
        ),
    ]
